language: php

php:
  - 5.3.2
  - 5.3
  - 5.4

branches:
  only:
    - develop

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --install-suggests

script: phpunit --coverage-text
